# Generated by Django 4.2.5 on 2023-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
