# Generated by Django 4.2.5 on 2023-09-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='opening_crawl',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='episode_id',
            new_name='id',
        ),
    ]
