# Generated by Django 4.2.5 on 2023-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('model', models.CharField(blank=True, max_length=150)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('cost_in_credits', models.CharField(blank=True, max_length=150)),
                ('length', models.CharField(blank=True, max_length=150)),
                ('starship_class', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
