# Generated by Django 4.2.5 on 2023-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, unique=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('height', models.IntegerField(blank=True)),
                ('mass', models.IntegerField(blank=True)),
                ('birth_year', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
