# Generated by Django 4.2.5 on 2023-09-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='mass',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
